### ISSUE TITLE
Planned QOL Improvements

### ISSUE THREAD

**Issue by RevoLand** [RevoLand/Steam-Library-Manager#63]
### Task Manager
- [x] ~Parallel File Transfer Toggle (#64 - [v1.5.1.9](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.5.1.9))~ (Removed/No use case)
  - [ ] Inform that slow transfer speeds might be caused by an AV software.
- [x] Continue on error for task manager tasks (#68) [[v1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.6.0.0)]
- [x] Ability to skip restart warning for Steam library related tasks (#69) [[v1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.6.0.0)]
- [x] Compress Origin games [[v1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.6.0.0)]
- [x] Ability to Auto Install Origin Games on task completion [[v1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.6.0.0)]
- [ ] Ability to Compact after moving a game
- [ ] Change compression method (#86)

### Library
- [x] Togglable Steam, Origin, Uplay library support [(Sneak-peek)](https://dl.dropboxusercontent.com/s/twy7b4jw3xqpmut/03-Saturday-j454qQ601034.gif) [[v1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.6.0.0)]
- [x] Library loading indicator [[v1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.6.0.0)]
- [ ] Indicator for backup libraries
- [ ] Detail View: With ability to trigger Compact status update etc directly from the view
- [ ] _(Long term)_ Added/Modified/Removed Apps (Library state caching - #55)

### Library Cleaner
- [x] Duplicate Game Finder/Cleaner (#73) [[v1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.6.0.0)]
- [ ] Sort order for library cleaner

### Other
- [x] Installation wizard for first time users [[v1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.6.0.0)]
- [x] Update Translation Keys [[v1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.6.0.0)]
- [x] Tabbed Settings [[v1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.6.0.0)]
- [ ] _(Long term)_ Custom theming support (Awaiting for v2 release of [MahApps.Metro](https://github.com/MahApps/MahApps.Metro))
- [ ] _(Long term)_ Redistributable Cleaner (With the way in my mind; md5 checking/symlinking files - #47)

List will be updated with time. All suggestions are welcome.
